# Generated by Django 5.2.5 on 2025-09-29 12:31

import istak_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istak_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.CharField(default=istak_backend.models.generate_12_digit_id, editable=False, max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
