# Generated by Django 5.2.1 on 2025-10-07 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istak_backend', '0002_alter_item_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['return_date'], name='istak_backe_return__d5a6c9_idx'),
        ),
    ]
