# Generated by Django 5.2.5 on 2025-10-14 04:10

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istak_backend', '0003_transaction_istak_backe_return__d5a6c9_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentOrgModerator',
            fields=[
            ],
            options={
                'verbose_name': 'Student Org Moderator',
                'verbose_name_plural': 'Student Org Moderators',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('istak_backend.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StudentOrgOfficer',
            fields=[
            ],
            options={
                'verbose_name': 'Student Org Officer',
                'verbose_name_plural': 'Student Org Officers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('istak_backend.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'user_web'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_managed', to=settings.AUTH_USER_MODEL),
        ),
    ]
