# Generated by Django 5.2.5 on 2025-10-14 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istak_backend', '0004_studentorgmoderator_studentorgofficer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='mobile_user',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'user_mobile'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
