# Generated by Django 5.2.5 on 2025-10-14 05:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istak_backend', '0005_alter_transaction_mobile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='borrow_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
