# Generated by Django 5.2.5 on 2025-10-15 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istak_backend', '0006_alter_transaction_borrow_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictiveItemCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_risk', models.FloatField(default=0.0)),
                ('reason', models.TextField(blank=True, null=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='istak_backend.item')),
            ],
        ),
    ]
