# Generated by Django 5.2.5 on 2025-10-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istak_backend', '0007_predictiveitemcondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='return_image',
            field=models.ImageField(blank=True, null=True, upload_to='borrower_return_images/'),
        ),
    ]
